{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd-tag-updater.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-tag-updater.labels" . | nindent 4 }}
{{- end }}
