apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-tag-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-tag-updater
subjects:
  - kind: ServiceAccount
    name: argocd-tag-updater
    namespace: argocd
