// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (in *TagUpdater) DeepCopyInto(out *TagUpdater) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TagUpdater) DeepCopy() *TagUpdater {
	if in == nil {
		return nil
	}
	out := new(TagUpdater)
	in.DeepCopyInto(out)
	return out
}

func (in *TagUpdater) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TagUpdaterList) DeepCopyInto(out *TagUpdaterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TagUpdater, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TagUpdaterList) DeepCopy() *TagUpdaterList {
	if in == nil {
		return nil
	}
	out := new(TagUpdaterList)
	in.DeepCopyInto(out)
	return out
}

func (in *TagUpdaterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PatchSpec) DeepCopyInto(out *PatchSpec) {
	*out = *in
}

func (in *PatchSpec) DeepCopy() *PatchSpec {
	if in == nil {
		return nil
	}
	out := new(PatchSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]PatchSpec, len(*in))
		copy(*out, *in)
	}
}

func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TagUpdaterSpec) DeepCopyInto(out *TagUpdaterSpec) {
	*out = *in
	out.Source = in.Source
	out.Interval = in.Interval
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ArgoCDApp != nil {
		in, out := &in.ArgoCDApp, &out.ArgoCDApp
		*out = new(ArgoCDAppRef)
		**out = **in
	}
}

func (in *TagUpdaterStatus) DeepCopyInto(out *TagUpdaterStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
